version: "3"

services:
  hub:
    image: selenium/hub
    ports: 
    - 4444:4444
  chromeNod:
    image: selenium/node-chrome-debug:latest
    depends_on: 
    - hub
    environment: 
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
    - 9001:5900
    links: 
    - hub
  firefoxNod:
    image: selenium/node-firefox-debug:latest
    depends_on: 
    - hub
    environment: 
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
    - 9002:5900
    links: 
    - hub