version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION:16
      - GRID_BROWSER_TIMEOUT:5000
      - GRID_TIMEOUT:5000
  chrome:
    image: selenium/node-chrome-debug:3.141.59
    ports:
      - "9002:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION:4
      - NODE_MAX_INSTANCES:4
    links:
      - selenium-hub

  firefox:
    image: selenium/node-firefox-debug:3.141.59
    ports:
      - "9001:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      -  HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION:4
      - NODE_MAX_INSTANCES:4
    links:
      - selenium-hub
